image: node:12
stages:
  - install
  - build
  - test
cache:
      paths:
        - node_modules/
install_dependencies:
      stage: install
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/
build:
      stage: build
      script:
        - npm run build
testing:
      stage: test
      script:
        - npm run test