// USER
export const FETCH_USER = 'FETCH_USER'

// AUTH
export const FETCH_AUTH = 'FETCH_AUTH'
export const RECEIVE_ITEM_AUTH = 'RECEIVE_ITEM_AUTH'
export const FAILED_AUTH = 'FAILED_AUTH'

// IMAGE
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const SUCCESS_IMAGE = 'SUCCESS_IMAGE'
export const FAILED_IMAGE = 'FAILED_IMAGE'

// SEARCH
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const RECEIVE_ITEM_SEARCH = 'RECEIVE_ITEM_SEARCH'
export const FAILED_SEARCH = 'FAILED_SEARCH'

// LOGIN
export const FETCH_LOGIN = 'FETCH_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'

// REGISTER
export const FETCH_REGISTER = 'FETCH_REGISTER'
export const RECEIVE_REGISTER = 'RECEIVE_REGISTER'
export const FAILED_REGISTER = 'FAILED_REGISTER'

// FORGOT PASSWORD
export const FETCH_FORGOT_PASSWORD = 'FETCH_FORGOT_PASSWORD'
export const RECEIVE_ITEM_FORGOT_PASSWORD = 'RECEIVE_ITEM_FORGOT_PASSWORD'
export const FAILED_FORGOT_PASSWORD = 'FAILED_FORGOT_PASSWORD'

// CHANGE PASSWORD
export const FETCH_CHANGE_PASSWORD = 'FETCH_CHANGE_PASSWORD'
export const RECEIVE_ITEM_CHANGE_PASSWORD = 'RECEIVE_ITEM_CHANGE_PASSWORD'
export const FAILED_CHANGE_PASSWORD = 'FAILED_CHANGE_PASSWORD'

// VERIFICATION
export const FETCH_VERIFICATION = 'FETCH_VERIFICATION'
export const SUCCESS_VERIFICATION = 'SUCCESS_VERIFICATION'
export const FAILED_VERIFICATION = 'FAILED_VERIFICATION'

// RESET PASSWORD
export const FETCH_RESET_PASSWORD = 'FETCH_RESET_PASSWORD'
export const SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD'
export const FAILED_RESET_PASSWORD = 'FAILED_RESET_PASSWORD'

// REGISTER VERIFICATION
export const FETCH_REGISTER_VERIFICATION = 'FETCH_REGISTER_VERIFICATION'
export const RECEIVE_REGISTER_VERIFICATION = 'RECEIVE_REGISTER_VERIFICATION'
export const FAILED_REGISTER_VERIFICATION = 'FAILED_REGISTER_VERIFICATION'

// RESEND VERIFICATION
export const FETCH_RESEND_VERIFICATION = 'FETCH_RESEND_VERIFICATION'
export const RECEIVE_RESEND_VERIFICATION = 'RECEIVE_RESEND_VERIFICATION'
export const FAILED_RESEND_VERIFICATION = 'FAILED_RESEND_VERIFICATION'

// SLIDER
export const FETCH_SLIDER = 'FETCH_SLIDER'
export const RECEIVE_SLIDER = 'RECEIVE_SLIDER'
export const FAILED_SLIDER = 'FAILED_SLIDER'

// HOME INTRO
export const FETCH_HOME_INTRO = 'FETCH_HOME_INTRO'
export const RECEIVE_HOME_INTRO = 'RECEIVE_HOME_INTRO'
export const FAILED_HOME_INTRO = 'FAILED_HOME_INTRO'

// TESTIMONIAL
export const FETCH_TESTIMONIAL = 'FETCH_TESTIMONIAL'
export const RECEIVE_TESTIMONIAL = 'RECEIVE_TESTIMONIAL'
export const FAILED_TESTIMONIAL = 'FAILED_TESTIMONIAL'

// ARTICLE
export const FETCH_ARTICLE = 'FETCH_ARTICLE'
export const RECEIVE_ITEM_ARTICLE = 'RECEIVE_ITEM_ARTICLE'
export const FAILED_ARTICLE = 'FAILED_ARTICLE'

// UPLOAD IMAGE
export const FETCH_UPLOAD_IMAGE = 'FETCH_UPLOAD_IMAGE'
export const RECEIVE_UPLOAD_IMAGE = 'RECEIVE_UPLOAD_IMAGE'
export const FAILED_UPLOAD_IMAGE = 'FAILED_UPLOAD_IMAGE'
export const RESET_UPLOAD_IMAGE = 'RESET_UPLOAD_IMAGE'
export const SET_FIRST_KEY = 'SET_FIRST_KEY'

// UPLOAD ORGANIZE
export const RECEIVE_STORE_SEARCH_PARAMS = 'RECEIVE_STORE_SEARCH_PARAMS'
export const RECEIVE_STORE_ORGANIZE = 'RECEIVE_STORE_ORGANIZE'
export const FAILED_STORE_ORGANIZE = 'FAILED_STORE_ORGANIZE'
export const UPDATE_STORE_STATE_ORGANIZE = 'UPDATE_STORE_STATE_ORGANIZE'

// EVENT
export const FETCH_EVENT = 'FETCH_EVENT'
export const RECEIVE_EVENT = 'RECEIVE_EVENT'
export const RESET_ITEM_EVENT = 'RESET_ITEM_EVENT'
export const RECEIVE_ITEM_EVENT = 'RECEIVE_ITEM_EVENT'
export const UPDATE_STATE_EVENT = 'UPDATE_STATE_EVENT'
export const FAILED_EVENT = 'FAILED_EVENT'

// CHANGE PASSWORD
export const FETCH_CREATE_EVENT = 'FETCH_CREATE_EVENT'
export const RECEIVE_ITEM_CREATE_EVENT = 'RECEIVE_ITEM_CREATE_EVENT'
export const FAILED_CREATE_EVENT = 'FAILED_CREATE_EVENT'

// ORGANIZER
export const SUCCESS_ORGANIZER = 'SUCCESS_ORGANIZER'
export const FETCH_ORGANIZER = 'FETCH_ORGANIZER'
export const RECEIVE_ORGANIZER = 'RECEIVE_ORGANIZER'
export const RECEIVE_ITEM_ORGANIZER = 'RECEIVE_ITEM_ORGANIZER'
export const UPDATE_STATE_ORGANIZER = 'UPDATE_STATE_ORGANIZER'
export const FAILED_ORGANIZER = 'FAILED_ORGANIZER'

// FACILITY
export const FETCH_FACILITY = 'FETCH_FACILITY'
export const RECEIVE_FACILITY = 'RECEIVE_FACILITY'
export const FAILED_FACILITY = 'FAILED_FACILITY'

// PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
export const RECEIVE_ITEM_PRODUCT = 'RECEIVE_ITEM_PRODUCT'
export const UPDATE_STATE_PRODUCT = 'UPDATE_STATE_PRODUCT'
export const FAILED_PRODUCT = 'FAILED_PRODUCT'

// CATEGORY
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY'
export const RECEIVE_ITEM_CATEGORY = 'RECEIVE_ITEM_CATEGORY'
export const UPDATE_STATE_CATEGORY = 'UPDATE_STATE_CATEGORY'
export const FAILED_CATEGORY = 'FAILED_CATEGORY'
